# Setup Podman container with home-assistant
#
# After installation on clean machine, the service is not running.
# Need reboot or:
#  $ sudo systemctl --user -M assistant@ start assistant
#
# Status:
#  $ sudo systemctl --user -M assistant@ status assistant
# Show log:
#  $ sudo su - assistant -c "journalctl --user -u assistant -f"

- hosts: localhost
  tasks:
  # See https://docs.fedoraproject.org/en-US/fedora-silverblue/troubleshooting/#_unable_to_add_user_to_group
  - name: Add group 'dialout'
    # Note that on reruns in same session, this will replace
    # a line containing assistant user, so create use will
    # run again
    ansible.builtin.lineinfile:
      path: /etc/group
      search_string: 'dialout:'
      line: 'dialout:x:18:'

  - name: Ensure group 'assistant' exists
    ansible.builtin.group:
      name: assistant
      state: present
      gid: 1002

  - name: Add the user 'assistant'
    ansible.builtin.user:
      name: assistant
      comment: assistant
      uid: 1002
      group: assistant
      # Add to group 'dialout' for ZigBee controller access via USB
      groups: dialout
      append: true

  - name: Ensure lingering enabled
    # This can be verified by
    #  $ ls -l /var/lib/systemd/linger/
    ansible.builtin.command:
      cmd: "loginctl enable-linger assistant"
      creates: /var/lib/systemd/linger/assistant

  - name: Allow Podman access to USB
    ansible.posix.seboolean:
      name: container_use_devices
      state: true
      persistent: true

  - name: Create systemd quad dir
    ansible.builtin.file:
      path: /home/assistant/.config/containers/systemd
      state: directory
      mode: '0755'
      owner: assistant
      group: assistant

  - name: Create systemd service
    # Quad file was not translated by generator
    # Apparently because the linger above had not taken effect yet
    # Solved by reboot, after which systemd was "running" for the user:
    #  $ ps aux | grep "systemd --user"
    #  assista+   ... /usr/lib/systemd/systemd --user
    #
    # Still a problem. Due to 'sudo su' not triggering correct login.
    # Need:
    #  $ sudo systemctl --user -M assistant@ daemon-reload
    #  $ sudo systemctl --user -M assistant@ --user list-unit-files
    ansible.builtin.template:
      src: assistant.container
      dest: /home/assistant/.config/containers/systemd/assistant.container
      owner: assistant
      group: assistant
    notify:
      - reload_systemd

  - name: Allow firewall access
    ansible.posix.firewalld:
      port: 8123/tcp
      permanent: true
      state: enabled

  handlers:
    - name: get assistant user id
      become: true
      become_user: assistant
      command: id -u
      register: myuid
      listen: reload_systemd

    - name: reload systemd
      become: true
      listen: reload_systemd
      become_user: assistant
      ansible.builtin.systemd_service:
        daemon_reload: yes
        scope: user
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ myuid.stdout }}"
