# Setup Podman container with home-assistant

- hosts: localhost

  tasks:
  # Access to the USB Zigbee device from Podman container
  #
  #  https://www.redhat.com/sysadmin/supplemental-groups-podman-containers
  #  https://discussion.fedoraproject.org/t/cannot-access-dev-ttyacm0-from-toolbox-container/13305
  #
  # Podman USB access inspection
  #
  #  As assistant-user, run sleep 1000, then as other user:
  #  $ ps -aeno "user,group,args" | grep sleep
  #      # assistant: sleep 1000
  #      1002     1002 sleep 1788
  #      # assistant: sg dialout -c 'sleep 1000'
  #      1002       18 sleep 1000
  #
  # Now with Podman.
  #  $ podman run -ti --annotation run.oci.keep_original_groups=1 --userns=keep-id --device /dev/ttyUSB0 ubi9 /bin/bash
  #
  #      # id:
  #      uid=1002(assistant) gid=1002(assistant) groups=1002(assistant)
  #      # sleep 1000:
  #      1002     1002 /usr/bin/coreutils --coreutils-prog-shebang=sleep /usr/bin/sleep 100
  #
  #
  # $ sg dialout -c 'podman run -ti --annotation run.oci.keep_original_groups=1 --userns=keep-id --device /dev/ttyUSB0 ubi9 /bin/bash'
  #
  #      # id:
  #       uid=1002(assistant) gid=18(dialout) groups=18(dialout),65534(nobody)
  #       (looks good! but still):
  #      # sleep 1000:
  #      1002     1002 /usr/bin/coreutils --coreutils-prog-shebang=sleep /usr/bin/sleep 1000


  # Add dialout group
  #
  #  $ stat /dev/ttyUSB0
  #  Access: (0666/crw-rw-rw-)  Uid: (    0/    root)   Gid: (   18/ dialout)

  # See https://docs.fedoraproject.org/en-US/fedora-silverblue/troubleshooting/#_unable_to_add_user_to_group
  - name: Add group 'dialout'
    ansible.builtin.lineinfile:
      path: /etc/group
      line: 'dialout:x:18:'

  - name: Ensure group 'assistant' exists
    ansible.builtin.group:
      name: assistant
      state: present
      gid: 1002

  - name: Add the user 'assistant'
    ansible.builtin.user:
      name: assistant
      comment: assistant
      uid: 1002
      group: assistant
      groups: dialout
      append: true


  - name: Ensure lingering enabled
    # This can be verified by
    #  $ ls -l /var/lib/systemd/linger/
    ansible.builtin.command:
      cmd: "loginctl enable-linger assistant"
      creates: /var/lib/systemd/linger/assistant

  - name: Allow Podman access to USB
    ansible.posix.seboolean:
      name: container_use_devices
      state: true
      persistent: true

  - name: Create systemd quad dir
    ansible.builtin.file:
      path: /home/assistant/.config/containers/systemd
      state: directory
      mode: '0755'
      owner: assistant
      group: assistant

  - name: Create systemd service
    # Quad file was not translated by generator
    # Apparently because the linger above had not taken effect yet
    # Solved by reboot, after which systemd was "running" for the user:
    #  $ ps aux | grep "systemd --user"
    #  assista+   ... /usr/lib/systemd/systemd --user
    #
    # Still a problem. Due to 'sudo su' not triggering correct login.
    # Need:
    #  $ sudo systemctl --user -M assistant@ daemon-reload
    #  $ sudo systemctl --user -M assistant@ --user list-unit-files
    ansible.builtin.template:
      src: assistant.container
      dest: /home/assistant/.config/containers/systemd/assistant.container
      owner: assistant
      group: assistant
    notify:
      - reload_systemd

  handlers:
    - name: reload_systemd
      ansible.builtin.systemd_service:
        daemon_reload: true
        
# XXX: can use manual systemctl --user commands to reload, TODO: via ansible

      # This works:
# podman run  --group-add 18 --name homeassistant   -e TZ=Europe/Copenhagen   -v /opt/data/home-assistant:/config:Z,rw   --cap-add=CAP_NET_RAW,CAP_NET_BIND_SERVICE   -p 8123:8123   --device /dev/ttyUSB0 -it  ghcr.io/home-assistant/home-assistant:stable

# XXX: testing this:
# podman run -ti --log-driver=journald --log-opt tag=assistant --group-add=keep-groups --name homeassistant --rm  -e TZ=Europe/Copenhagen   -v /opt/data/services/assistant:/config:Z,rw   --cap-add=CAP_NET_RAW,CAP_NET_BIND_SERVICE   -p 8123:8123   --device /dev/ttyUSB0 -it  ghcr.io/home-assistant/home-assistant:stable
