# Build with:
#  podman build -f Containerfile -t lms
#
# Release with:
# podman build -f Containerfile -t docker.io/jskov/lms:8.4.0-ubi9.3-10_000
# podman push (above name:label)

FROM registry.access.redhat.com/ubi9/ubi-init:9.3-10

RUN dnf -y --nodocs install perl \
 && dnf clean all \
 && cp /usr/share/zoneinfo/Europe/Copenhagen /etc/localtime \
 && echo "54f47b937daf8142c8681954a32559bcba1b446ed78d511159b5361b8cde6fd8  /tmp/lms.rpm" > /tmp/shasums.txt \
 && curl https://downloads.slimdevices.com/LogitechMediaServer_v8.4.0/logitechmediaserver-8.4.0-1.noarch.rpm -o /tmp/lms.rpm \
 && sha256sum -c /tmp/shasums.txt \
 && rpm -i /tmp/lms.rpm \
 && rm -f /tmp/lms.rpm /tmp/shasums.txt






