# Setup Podman container with Logitech Media Server
#
# After installation on clean machine, the service is not running.
# Need reboot or:
#  $ sudo systemctl --user -M lms@ start lms
#
# Status:
#  $ sudo systemctl --user -M lms@ status lms
# Show log:
#  $ sudo su - lms -c "journalctl --user -u lms -f"

- hosts: localhost
  tasks:
  - name: Ensure group 'lms' exists
    ansible.builtin.group:
      name: lms
      state: present
      gid: 1003

  - name: Add the user 'lms'
    ansible.builtin.user:
      name: lms
      comment: lms
      uid: 1003
      group: lms

  - name: Ensure lingering enabled
    # This can be verified by
    #  $ ls -l /var/lib/systemd/linger/
    ansible.builtin.command:
      cmd: "loginctl enable-linger lms"
      creates: /var/lib/systemd/linger/lms

  - name: Create systemd quad dir
    ansible.builtin.file:
      path: /home/lms/.config/containers/systemd
      state: directory
      mode: '0755'
      owner: lms
      group: lms

  - name: Create systemd service
    ansible.builtin.template:
      src: lms.container
      dest: /home/lms/.config/containers/systemd/lms.container
      owner: lms
      group: lms
    notify:
      - reload_systemd

  - name: Allow firewall access
    ansible.posix.firewalld:
      port: 9000/tcp
      permanent: true
      state: enabled

  handlers:
    - name: get lms user id
      become: true
      become_user: lms
      command: id -u
      register: myuid
      listen: reload_systemd

    - name: reload systemd
      become: true
      listen: reload_systemd
      become_user: lms
      ansible.builtin.systemd_service:
        daemon_reload: yes
        scope: user
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ myuid.stdout }}"
